---
- name: '{{ launchd_timer_name }} Create check script'
  copy:
    src:  'check.sh'
    dest: '{{ launchd_timer_consul_check_path }}'
    mode: 0755

- name: Create Consul service definition
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name: '{{ launchd_timer_consul_service_id }}'
    consul_services:
      - id:      '{{ launchd_timer_consul_service_id }}'
        name:    '{{ launchd_timer_consul_service_name }}'
        tags:    '{{ launchd_timer_consul_tags }}'
        meta:    '{{ launchd_timer_consul_meta }}'
        address: '{{ launchd_timer_consul_address }}'
        checks:
          - name: '{{ launchd_timer_consul_service_name }}-rest-health'
            type: 'script'
            script: >-
              {{ launchd_timer_consul_check_path }}
              {%- if launchd_timer_consul_warning %} --warning{% endif %}
              {%- if not launchd_timer_enabled %} --disabled{% endif %}
              --name={{ launchd_timer_name }}
